# Generated by Django 5.2.3 on 2026-06-21 21:16

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_novice', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BreakChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('open', 'Open semifinals'), ('novice', 'Novice final')], max_length=10)),
                ('debater', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='break_choice', to='tournament.debater')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('debater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_slots', to='tournament.debater')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('prelim', 'Preliminary'), ('open_semifinal', 'Open semifinal'), ('open_final', 'Open final'), ('novice_final', 'Novice final')], default='prelim', max_length=30)),
                ('silent', models.BooleanField(default=False)),
                ('draw_published', models.BooleanField(default=False)),
                ('results_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['number', 'id'],
                'unique_together': {('number', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='tournament.round')),
            ],
            options={
                'ordering': ['ordinal'],
                'unique_together': {('round', 'ordinal')},
            },
        ),
        migrations.CreateModel(
            name='BallotToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by_name', models.CharField(blank=True, max_length=200)),
                ('submitted_by_email', models.EmailField(blank=True, max_length=254)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballot_tokens', to='tournament.room')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballot_tokens', to='tournament.round')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(default='Shuffle Cup', max_length=200)),
                ('final_tab_published', models.BooleanField(default=False)),
                ('current_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.round')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.society')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='debater',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.society'),
        ),
        migrations.CreateModel(
            name='SpeakerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confirmed', models.BooleanField(default=False)),
                ('participant_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_score', to='tournament.participantslot')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_scores', to='tournament.room')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_scores', to='tournament.round')),
            ],
        ),
        migrations.CreateModel(
            name='SwingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, choices=[('OG', 'OG'), ('OO', 'OO'), ('CG', 'CG'), ('CO', 'CO')], max_length=2)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swings', to='tournament.room')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swings', to='tournament.round')),
            ],
            options={
                'unique_together': {('round', 'display_name')},
            },
        ),
        migrations.AddField(
            model_name='participantslot',
            name='swing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_slots', to='tournament.swingslot'),
        ),
        migrations.CreateModel(
            name='TemporaryPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('OG', 'OG'), ('OO', 'OO'), ('CG', 'CG'), ('CO', 'CO')], max_length=2)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='tournament.room')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='tournament.round')),
            ],
            options={
                'ordering': ['room__ordinal', 'id'],
                'unique_together': {('room', 'position')},
            },
        ),
        migrations.AddField(
            model_name='participantslot',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='tournament.temporarypair'),
        ),
        migrations.CreateModel(
            name='PairResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team_points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('advances', models.BooleanField(default=False)),
                ('champion', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_results', to='tournament.room')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_results', to='tournament.round')),
                ('temporary_pair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='tournament.temporarypair')),
            ],
        ),
        migrations.CreateModel(
            name='DebaterPartnerConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('debater_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_conflicts_a', to='tournament.debater')),
                ('debater_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_conflicts_b', to='tournament.debater')),
            ],
            options={
                'unique_together': {('debater_a', 'debater_b')},
            },
        ),
        migrations.CreateModel(
            name='JudgeDebaterConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('debater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_conflicts', to='tournament.debater')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debater_conflicts', to='tournament.judge')),
            ],
            options={
                'unique_together': {('judge', 'debater')},
            },
        ),
        migrations.CreateModel(
            name='JudgeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chair', 'Chair'), ('panel', 'Panel')], max_length=10)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='tournament.judge')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_allocations', to='tournament.room')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_allocations', to='tournament.round')),
            ],
            options={
                'unique_together': {('room', 'judge')},
            },
        ),
        migrations.AddConstraint(
            model_name='participantslot',
            constraint=models.UniqueConstraint(fields=('pair', 'order'), name='unique_pair_slot'),
        ),
    ]
