# Generated by Django 5.2.3 on 2026-06-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_remove_conflict_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakchoice',
            name='choice',
            field=models.CharField(choices=[('open', 'Semifinais Open'), ('novice', 'Final novice')], max_length=10),
        ),
        migrations.AlterField(
            model_name='round',
            name='kind',
            field=models.CharField(choices=[('prelim', 'Preliminar'), ('open_semifinal', 'Semifinal Open'), ('open_final', 'Final Open'), ('novice_final', 'Final novice')], default='prelim', max_length=30),
        ),
    ]
