# Generated by Django 5.2.3 on 2026-06-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_judge_private_urls_and_unique_allocations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='kind',
            field=models.CharField(choices=[('prelim', 'Preliminar'), ('open_semifinal', 'Semifinal Open'), ('open_final', 'Final')], default='prelim', max_length=30),
        ),
        migrations.DeleteModel(
            name='BreakChoice',
        ),
    ]
