# Generated by Django 5.2.3 on 2026-06-27 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_alter_round_kind_delete_breakchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundUnavailableDebater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_unavailabilities', to='tournament.debater')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_debaters', to='tournament.round')),
            ],
            options={
                'ordering': ['debater__name'],
                'unique_together': {('round', 'debater')},
            },
        ),
    ]
